### ISSUE TITLE
TypeError: read_csv() takes 1 positional argument but 2 positional arguments (and 2 keyword-only arguments) were given

### ISSUE THREAD

**Issue by sdcampbell** [MoooKitty/pypipal#1]
Hello, 
First I want to thank you for your work and sharing Pypipal with the public! I've been using it for a long time and this is the first time I've had any errors so I'm guessing this is probably an issue with a change in Pandas.
Output:
```
python3 pypipal.py -f pypipal.txt -o output.xlsx
Traceback (most recent call last):
  File "/home/steve/crackjob/pypipal/pypipal.py", line 276, in <module>
    main(args)
  File "/home/steve/crackjob/pypipal/pypipal.py", line 12, in main
    data = pd.read_csv(args.infile, args.sep, header=None, names=['Hash','Password'])
TypeError: read_csv() takes 1 positional argument but 2 positional arguments (and 2 keyword-only arguments) were given
```
I did check that my input is in the right format, and also checked to make sure that the : character isn't in any of the passwords.

If I can find some free time soon I'll see what I can do to help fix this.

Thanks!

**Comment by eduardo010174** [comment]
Change 
line 12 to
data = pd.read_csv(args.infile, delimiter=args.sep, header=None, names=['Hash','Password'])

Fix other error on write o xlsx
line 267
writer._save()

Test if fix your problems.
If it's work for you i will make pull request for fix this bug.

**Comment by sdcampbell** [comment]
I made the changes. Now I have a new error: 
```
Traceback (most recent call last):
  File "/home/steve/crackjob/pypipal/pypipal.py", line 276, in <module>
    main(args)
  File "/home/steve/crackjob/pypipal/pypipal.py", line 16, in main
    data['Baseword'] = data.Password.str.replace(r'[^a-zA-Z]*$', '')
  File "/home/steve/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 6204, in __getattr__
    return object.__getattribute__(self, name)
  File "/home/steve/.local/lib/python3.10/site-packages/pandas/core/accessor.py", line 224, in __get__
    accessor_obj = self._accessor(obj)
  File "/home/steve/.local/lib/python3.10/site-packages/pandas/core/strings/accessor.py", line 190, in __init__
    self._inferred_dtype = self._validate(data)
  File "/home/steve/.local/lib/python3.10/site-packages/pandas/core/strings/accessor.py", line 244, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!. Did you mean: 'std'?
```
Thank you

**Comment by sdcampbell** [comment]
I figured out how to fix it. Change line 16 from:
data['Baseword'] = data.Password.str.replace(r'[^a-zA-Z]*$', '')
To:
data['Baseword'] = data.Password.astype(str).str.replace(r'[^a-zA-Z]*$', '')

Edit: This broke it in another way which resulted in NaN being the most frequent password. See my commits and pull request for the fix.
